### PR TITLE
Cleaning ES6 style

### PR DESCRIPTION
**Pull request by pnodet**
**Mostly using es-lint to clean the code**

• Use arrow functions for terseness

• Get rid of `var` keyword
• Avoid comparing to itself
• Prefer Number.isFinite() over isFinite()
• Prefer Number.isNaN() over isNaN()
• No-multi-assign ( is.a = is.type = ... )

**Add support for**

• Map
• WeakMap
• Set
• WeakSet
• Promise
• Safe Integer
• Float

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
Absolutely not.

1. this is a breaking change. This package supports ES3 browsers and will continue to do so - so we can NEVER EVER EVER use arrow functions or let/const, unless we add babel, which is also not worth the complexity.
2. Styling changes are churn that is rarely worth it.
3. Unsolicited, undiscussed PRs that make major changes to how a project works are actually insanely rude and inappropriate.

**Comment by pnxdxt** [comment]
Sorry if it offended you.

I wanted a fork of this useful `is` object including :
• Map
• WeakMap
• Set
• WeakSet
• Promise
• Safe Integer
• Float

So I forked the project and made a few changes.
I thought making a PR was a quick way to know if you liked the changes. Sorry for the inconvenience.

**Comment by ljharb** [comment]
Why? What’s the difference how it’s authored?

**Comment by ljharb** [comment]
If you want more predicates, those already exist as separate packages:
 - https://npmjs.com/is-weakmap
 - https://npmjs.com/is-map
 - https://npmjs.com/is-set
 
 etc

**Pull request closed without merging**
